### ISSUE TITLE
500 on /fantasy Slash Command

### ISSUE THREAD

**Issue by kabirsikand** [landonp1203/yahoo-fantasy-bot#17]
Slack slash commands return 500s. See the following setup and output from the bot. Looks like a JSON parsing issue, perhaps with newer slack api's?

Slack settings:
```
Command: /fantasy
Request URL: http://mmt-ff-bot.herokuapp.com/message
Short Description: FantasyBot Commands
Usage Hint: 'help' for full command list
```

Output in Bot (Heroku):
```
2019-09-03T22:56:13.883702+00:00 heroku[router]: at=info method=POST path="/message" host=mmt-ff-bot.herokuapp.com request_id=6584ae8e-93f8-4fdd-b701-0badc8c6d348 fwd="1.2.3.4" dyno=web.1 connect=0ms service=8ms status=500 bytes=215 protocol=http
2019-09-03T22:56:13.885385+00:00 app[web.1]: [ERROR] [qtp1180078417-24] 2019-09-03 22:56:13,879 [spark.http.matching.GeneralError] - 
2019-09-03T22:56:13.885423+00:00 app[web.1]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
2019-09-03T22:56:13.885426+00:00 app[web.1]: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:505) ~[web-server-all.jar:?]
2019-09-03T22:56:13.885429+00:00 app[web.1]: 	at org.json.JSONObject.<init>(JSONObject.java:215) ~[web-server-all.jar:?]
2019-09-03T22:56:13.885431+00:00 app[web.1]: 	at org.json.JSONObject.<init>(JSONObject.java:399) ~[web-server-all.jar:?]
2019-09-03T22:56:13.885433+00:00 app[web.1]: 	at web.Server.lambda$registerRoutes$2(Server.java:47) ~[web-server-all.jar:?]
2019-09-03T22:56:13.885435+00:00 app[web.1]: 	at spark.RouteImpl$1.handle(RouteImpl.java:72) ~[web-server-all.jar:?]
2019-09-03T22:56:13.885437+00:00 app[web.1]: 	at spark.http.matching.Routes.execute(Routes.java:61) ~[web-server-all.jar:?]
2019-09-03T22:56:13.885440+00:00 app[web.1]: 	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130) [web-server-all.jar:?]
2019-09-03T22:56:13.885443+00:00 app[web.1]: 	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [web-server-all.jar:?]
2019-09-03T22:56:13.885445+00:00 app[web.1]: 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) [web-server-all.jar:?]
2019-09-03T22:56:13.885447+00:00 app[web.1]: 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [web-server-all.jar:?]
2019-09-03T22:56:13.885449+00:00 app[web.1]: 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [web-server-all.jar:?]
2019-09-03T22:56:13.885452+00:00 app[web.1]: 	at org.eclipse.jetty.server.Server.handle(Server.java:530) [web-server-all.jar:?]
2019-09-03T22:56:13.885454+00:00 app[web.1]: 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347) [web-server-all.jar:?]
2019-09-03T22:56:13.885456+00:00 app[web.1]: 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256) [web-server-all.jar:?]
2019-09-03T22:56:13.885458+00:00 app[web.1]: 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [web-server-all.jar:?]
2019-09-03T22:56:13.885460+00:00 app[web.1]: 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [web-server-all.jar:?]
2019-09-03T22:56:13.885463+00:00 app[web.1]: 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [web-server-all.jar:?]
2019-09-03T22:56:13.885465+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [web-server-all.jar:?]
2019-09-03T22:56:13.885467+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [web-server-all.jar:?]
2019-09-03T22:56:13.885470+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [web-server-all.jar:?]
2019-09-03T22:56:13.885472+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382) [web-server-all.jar:?]
2019-09-03T22:56:13.885475+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708) [web-server-all.jar:?]
2019-09-03T22:56:13.885477+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626) [web-server-all.jar:?]
2019-09-03T22:56:13.885480+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222-heroku]
```

**Comment by kabirsikand** [comment]
I think it is this line:
https://github.com/landonp1203/yahoo-fantasy-bot/blob/master/web-server/src/main/java/web/CommandInterpreter.java#L9

And:
https://github.com/landonp1203/yahoo-fantasy-bot/blob/master/web-server/src/main/java/web/CommandInterpreter.java#L19

The 'message' passed in actually does not include the 'command' that was sent.

**Comment by landonp1203** [comment]
So the commands sent from the messaging services was actually a super duper experiment on my part and I never put it on a feature branch, which I should have and kept it off master/dev.  As of now, I am working on getting the no commands bot working, and then migrating over to the commands version.  I’m planning to have a couple different flavors of this bot for people’s usage however they please.  As of now, I’m shooting for probably week 2-3 to have the commands and other flavors of the bot ready to go.

**Comment by landonp1203** [comment]
Closing this in favor of a issue created to track commands flavored bot.
