### ISSUE TITLE
Trade alert not shown

### ISSUE THREAD

**Issue by Cryzin** [landonp1203/yahoo-fantasy-bot#55]
Hello,

Publishing to discord via webhook. We had a trade that happened 5 hours ago, that wasn't alerted.

**Comment by landonp1203** [comment]
Can you paste the logs in here?

**Comment by landonp1203** [comment]
What league are you using? From my understanding, NFL leagues are not currently being run because we are not in season.

**Comment by Cryzin** [comment]
NFL. We started our draft early since we are all craving football.

**Comment by landonp1203** [comment]
Please paste your logs when you get a chance.

**Comment by Cryzin** [comment]
How do I do that, please?

**Comment by Cryzin** [comment]
Now it doesn't even show the discord errors. Just

`2020-07-10T17:01:39.969924+00:00 app[bot.1]: Attempting to save last time checked...1594400499

2020-07-10T17:01:39.972195+00:00 app[bot.1]: Latest time has been saved.

2020-07-10T17:01:54.818169+00:00 app[bot.1]: Grabbing Data...

2020-07-10T17:01:55.019063+00:00 app[bot.1]: Data grabbed.

2020-07-10T17:01:55.032326+00:00 app[bot.1]: More than 20 entries in the latest_time table.  Removing top 20.

2020-07-10T17:01:55.069219+00:00 app[bot.1]: Attempting to save last time checked...1594400515

2020-07-10T17:01:55.075411+00:00 app[bot.1]: Latest time has been saved.

2020-07-10T17:02:09.816867+00:00 app[bot.1]: Grabbing Data...

2020-07-10T17:02:09.976457+00:00 app[bot.1]: Data grabbed.

2020-07-10T17:02:09.979487+00:00 app[bot.1]: Attempting to save last time checked...1594400529

2020-07-10T17:02:09.981268+00:00 app[bot.1]: Latest time has been saved.

2020-07-10T17:02:24.816949+00:00 app[bot.1]: Grabbing Data...

2020-07-10T17:02:24.946086+00:00 app[bot.1]: Data grabbed.

2020-07-10T17:02:24.948729+00:00 app[bot.1]: Attempting to save last time checked...1594400544

2020-07-10T17:02:24.950565+00:00 app[bot.1]: Latest time has been saved.`

**Comment by landonp1203** [comment]
Hmmm okay so there is an error with the messages getting sent, I'm wondering if you entered the Discord Webhook URL incorrectly.

**Comment by Cryzin** [comment]
Hello,

After that screenshot I had re-entered the discord webhook. Also prior to the error it was sending messages without problem. 

I deleted and re-set it up and it was not showing any changes at all in the logs.

**Comment by landonp1203** [comment]
So has the issue been fixed with deleting and standing the dyno up again?  I can't tell from your last message.

**Comment by Cryzin** [comment]
Sorry, it is not.

**Comment by landonp1203** [comment]
Try taking a look at #57

**Comment by Cryzin** [comment]
Hello,

So I deleted an re-deployed the app and I get below error now.

`

2020-07-21T04:10:56.588421+00:00 heroku[web.1]: State changed from starting to crashed

2020-07-21T04:10:58.897761+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=HIDDEN request_id=HIDDEN fwd="70.59.77.55" dyno= connect= service= status=503 bytes= protocol=https

2020-07-21T04:10:59.336053+00:00 app[bot.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8 

2020-07-21T04:10:59.539358+00:00 app[bot.1]: Exception in thread "main" exceptions.GameKeyException: Game key (nfl) is not a valid game key.  Valid options are (NFL, NBA, MLB).  Please fix and restart dynos.

2020-07-21T04:10:59.539535+00:00 app[bot.1]: 	at shared.EnvVariablesChecker.checkGameKey(EnvVariablesChecker.kt:25)

2020-07-21T04:10:59.539618+00:00 app[bot.1]: 	at shared.EnvVariablesChecker.check(EnvVariablesChecker.kt:10)

2020-07-21T04:10:59.539701+00:00 app[bot.1]: 	at bot.Bot.main(Bot.kt:9)

2020-07-21T04:10:59.540233+00:00 app[bot.1]: 	at bot.Bot.main(Bot.kt)

2020-07-21T04:10:59.610993+00:00 heroku[bot.1]: Process exited with status 1

2020-07-21T04:10:59.679865+00:00 heroku[bot.1]: State changed from up to crashed`

**Comment by landonp1203** [comment]
lol...give me a sec, I forgot that string equality checks the case as well :)

**Comment by landonp1203** [comment]
@Cryzin try now

**Comment by Cryzin** [comment]
Currently:

> 2020-07-21T04:20:23.946455+00:00 heroku[bot.1]: State changed from crashed to starting
> 
> 2020-07-21T04:20:27.790987+00:00 heroku[bot.1]: Starting process with command `java -jar build/libs/bot.jar`
> 
> 2020-07-21T04:20:28.628686+00:00 heroku[bot.1]: State changed from starting to up
> 
> 2020-07-21T04:20:30.634757+00:00 heroku[bot.1]: Process exited with status 1
> 
> 2020-07-21T04:20:30.695554+00:00 heroku[bot.1]: State changed from up to crashed
> 
> 2020-07-21T04:20:30.400712+00:00 app[bot.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8 
> 
> 2020-07-21T04:20:30.551390+00:00 app[bot.1]: Grabbing Data...
> 
> 2020-07-21T04:20:30.565143+00:00 app[bot.1]: Exception in thread "main" java.lang.ExceptionInInitializerError
> 
> 2020-07-21T04:20:30.565491+00:00 app[bot.1]: 	at bot.Bot.main(Bot.kt:10)
> 
> 2020-07-21T04:20:30.565586+00:00 app[bot.1]: 	at bot.Bot.main(Bot.kt)
> 
> 2020-07-21T04:20:30.565846+00:00 app[bot.1]: Caused by: java.lang.NullPointerException
> 
> 2020-07-21T04:20:30.566410+00:00 app[bot.1]: 	at bot.utils.DataRetriever.grabData(DataRetriever.kt:82)
> 
> 2020-07-21T04:20:30.566501+00:00 app[bot.1]: 	at bot.utils.DataRetriever.retrieveGameKey(DataRetriever.kt:93)
> 
> 2020-07-21T04:20:30.566628+00:00 app[bot.1]: 	at bot.utils.DataRetriever.<clinit>(DataRetriever.kt:25)
> 
> 2020-07-21T04:20:30.566794+00:00 app[bot.1]: 	... 2 more

**Comment by Cryzin** [comment]
Also just wanted to make you aware of this typo

![image](https://user-images.githubusercontent.com/1764503/88012805-59819f00-cb0a-11ea-9322-d54e9ef40fff.png)

**Comment by landonp1203** [comment]
Guess I was tired doing that part months ago, I'll swing around and get it tomorrow...thanks!

**Comment by landonp1203** [comment]
As for the exception, I'll have to grab that after work tomorrow since it's almost 1am here.  It worked on my end, odd why it didn't in Heroku.

**Comment by Cryzin** [comment]
No worries, and thank you for your time.

**Comment by landonp1203** [comment]
Try it now, it was an order of operations with the OAuth2 service being built after the call when it was needed before @Cryzin

**Comment by landonp1203** [comment]
Don't try it, I broke something...sorry its late :/

**Comment by landonp1203** [comment]
Fixed with https://github.com/landonp1203/yahoo-fantasy-bot/commit/4fa0a356db9d76d105913131c6bbc9553f857e08 @Cryzin
